### ISSUE TITLE
Can not copy and paste to/from Linux clipboard

### ISSUE THREAD

**Issue by kmm2** [snapcrafters/dosbox-x#15]
Config option "clip_key_modifier" does not exist.

Copy and paste work in v0.83.1 for Windows properly.

**Comment by rderooy** [comment]
copy and paste, as mentioned in the docs is currently a Windows only feature.

**Comment by rderooy** [comment]
copy and paste should work in the meantime with recent builds.

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting!

I can confirm this works in the latest version, so I'm closing this.
