### ISSUE TITLE
Config file is not included.

### ISSUE THREAD

**Issue by CHJ85** [snapcrafters/dosbox-x#16]
HI there. The file dosbox-x-<version-number>.conf file is not included, and configurations from the GUI won't save.
Only reason I went with the Snap package is because Dosbox-x is not packaged for Ubuntu.
I also tried to compile it from source which didn't work because there were missing libraries.

**Comment by rderooy** [comment]
You should be able to generate one, by running inside dosbox-x:
```
config -wcd -all
```

**Comment by CHJ85** [comment]
Thank you.
