### ISSUE TITLE
dosbox-x snap does not start

### ISSUE THREAD

**Issue by rderooy** [snapcrafters/dosbox-x#18]
@popey I decided to have a look at the Snap package, to see how it compares to the Flatpak I made. And if I could perhaps add some contributions. But I immediately run into a problem. Namely, it does not start. Neither from the desktop by clicking on the icon or from the command line. The command line though gives at least a hint as to what is going on.

```
$ snap info dosbox-x
name:      dosbox-x
summary:   DOSBox-X fork of the DOSBox project
publisher: Snapcrafters
store-url: https://snapcraft.io/dosbox-x
contact:   https://github.com/snapcrafters/dosbox-x/issues
license:   unset
description: |
  DOSBox-X is a x86 emulator with Tandy/Hercules/CGA/EGA/VGA/SVGA graphics
  sound and DOS. It's been designed to run old DOS games under platforms that
  don't support it.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - dosbox-x
snap-id:      ogcav3zrjqBXdDx8ofgJYMEPSLVRs9ID
tracking:     latest/stable
refresh-date: today at 09:17 CEST
channels:
  latest/stable:    0.83.6 2020-10-02 (597) 80MB -
  latest/candidate: ↑                            
  latest/beta:      0.83.6 2020-10-02 (597) 80MB -
  latest/edge:      0.83.5 2020-10-06 (603) 79MB -
installed:          0.83.6            (597) 80MB -
```

```
$ snap run dosbox-x
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
LOG: Early LOG Init complete
LOG: Logging init: beginning logging proper. This is the end of the early init logging
LOG: Logging: No logfile was given. All further logging will be discarded.
LOG: DOSBox-X version 0.83.6 (Linux SDL1)
LOG: E_Exit: Can't init SDL No available video device
E_Exit: Can't init SDL No available video device
```

Any idea what may be causing this? I'm running Fedora 33 beta with Wayland.

Two other things I noticed.
- It still uses the regular dosbox icon on the linux desktop, and not the dosbox-x icon. Please also note that there is a SVG icon available in dosbox-x under contrib/icons which should be used where possible.
- Your using the SDL1 build apparently based on the above LOG messages, even though from the snapcract.yaml it seems like it should be SDL2?

**Comment by rderooy** [comment]
a quick test confirmed my suspicion.

Switching over to Xorg for a moment allows it to run. So the problem seems to be that snap is trying to force the app to run in wayland mode, and SDL has been compiled without wayland support. Probably because it is the SDL1 version, which I don't think supports wayland. But even if you where to compile the SDL2 version instead things would not work properly as there are problems with SDL2 on Wayland with the Gnome desktop (Mutter issue), namely that the window decorations will be missing. So somehow you should instruct snap to use xorg (xwayland).

**Comment by rderooy** [comment]
Also, when run in X11 I can confirm that fluidsynth support was not compiled in. And that there is an error from ALSA which prevents external MIDI synths from being used.

**Comment by rderooy** [comment]
Seems this is a known problem with no real solution for now
https://forum.snapcraft.io/t/apps-wont-run-and-crash-on-gnome-wayland/20322/7

**Comment by popey** [comment]
Thanks for the feedback, much appreciated. I've made a PR to disable wayland for the moment. I'll take a look at the ALSA issue separately.

**Comment by popey** [comment]
![Screenshot from 2020-10-08 15-33-32](https://user-images.githubusercontent.com/1841272/95473241-cecb7600-097b-11eb-8581-8cd6f3d8ab43.png)

Tested under wayland on Fedora in a VM. Looks okay to me! :D
Thanks again @rderooy

**Comment by rderooy** [comment]
Hmm... looking at that screenshot, there is clearly something wrong.

The window size is messed up, it uses too much vertical space. The banner
should be at the top, just below the menu bar and instead there is
additional space in between. And the same at the bottom of the window.

Speaking of the menu bar, 2 options are blacked out. "Capture" and "Drive".

No idea what is going on here.

p.s. Why did you not do a SDL2 build? (run the build-debug-sdl2 script).
Also the debug does not mean the binary has additional debug data, just
that you have a debugger option as a menu option to debug DOS programs.
