### ISSUE TITLE
Changes requested

### ISSUE THREAD

**Issue by rderooy** [snapcrafters/dosbox-x#20]
Hi,

I would like to ask for a few things to be changed for building the snap package. Such that the snap and flatpak experiences are more in-line with each other. fyi, I created the flatpak package.

- [x] #27
  - This can be accomplished by simply changing from the "build" script to the "build-debug-sdl2" script. Note that "debug" here does NOT refer to adding debug code to dosbox-x itself, but rather to enable a debugger feature option that allows debugging DOS applications running in dosbox-x.
  - In addition change references from SDL 1.2 to SDL2 in the yaml file to match
- [x] #28
  - For the flatpak, I use FluidSynth v2 as it offers superior MIDI quality over v1.
- [x] #29
- [x] #30
  - You can find some recent screenshots here: https://github.com/joncampbell123/dosbox-x/tree/master/contrib/linux
- [x] #31
  - https://github.com/joncampbell123/dosbox-x/tree/master/contrib/linux

A new dosbox-x release should be out around the 1st of the month, and I will be preparing some minor updates to the flatpak yaml for the next version. For instance, right now the flatpak page does not show any screenshots, but once the new build is done with the updated metainfo.xml, screenshots will be shown.

**Comment by merlijn-sebrechts** [comment]
Thanks for this report! We finally fixed all these issues, so I'm closing it!
