### ISSUE TITLE
use the SVG icon where possible. For instance the icon here https://snapcraft.io/dosbox-x has a white background (non-transparent).

### ISSUE THREAD

**Issue by lucyllewy** [snapcrafters/dosbox-x#29]

**Comment by mr-cal** [comment]
I updated the logo on the snap store, but I don't know if the store actually supports SVGs.

The SVG I uploaded was converted to `dosbox-x.svg.png` :(

**Comment by merlijn-sebrechts** [comment]
@mr-cal The change succeeded. It's indeed converted to a png, but one with a transparent background now!

We're slowly moving to using the `snapcraft.yaml` metadata as the source for the listing of every snap. Before we can turn it on, however, we need the snapcraft.yaml metadata to reflect the store listing. **Can you add the `icon` field in the snapcraft.yaml metadata, so we're sure that we're not overwriting the good icon in the store once we turn it on?**

Thanks!
