### ISSUE TITLE
No audio output.

### ISSUE THREAD

**Issue by pizzadude** [snapcrafters/dosbox-x#7]
There is no audio output.
Tested with wolfenstein 3D and "skunny kart".
Using --edge build

Regular non-snapped dosbox from ppa:i30817/dosbox-patched works fine with audio.

I use Linux Mint 19.1.

Might be because the games use midi?

**Comment by popey** [comment]
Thanks for the bug report. I'll take a look. We've certainly had MIDI issues in other snaps.

**Comment by pizzadude** [comment]
Thanks!
